<?php

require_once("../autoloader.php");

use Prototype\Livro;

$inicio1 = microtime(true);

$compradores = [
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V',
    'Gabriel Anhaia',
    'Anderson Scherer',
    'Braian Ottoni',
    'Miss Edward Kerluke',
    'Otis Gusikowski',
    'Stacey Kozey PhD',
    'Preston Mayer',
    'Harvey Ortiz',
    'Godfrey Carroll',
    'Chanelle Littel DDS',
    'Bertha Jewess',
    'Waldo Rath',
    'Freeman Wisozk',
    'Jeffry Kautzer PhD',
    'Dawn Ward',
    'Ms. Maximus Wisoky',
    'Thea Block',
    'Bethany Davis',
    'Tia Luettgen',
    'Rosella Farrell',
    'Kyle Eichmann',
    'Ms. Emmitt Orn',
    'Ms. Korey Witting',
    'Charles Jacobs PhD',
    'Mrs. Christina Zboncak',
    'Tressa Schneider',
    'Dewitt Hoeger',
    'Bertrand Murphy',
    'Peggie O Connell',
    'Mr. Bella Stoltenberg',
    'Liliana Hane',
    'Jaunita Cruickshank',
    'Demetrius Stark DVM',
    'Lynn Gaylord',
    'Anderson Franecki',
    'Reymundo Donnelly III',
    'Chanel Gulgowski',
    'Levi Ankunding',
    'Bella Herman PhD',
    'Nicholaus Harªann',
    'Alessandro Schultz',
    'Francisca Anderson',
    'Taylor Haley',
    'Dashawn Hettinger',
    'Dr. Kallie McDermott',
    'Avis Becker',
    'Courtney Mertz III',
    'Joannie Christiansen DDS',
    'Bertram Terry',
    'Ignacio Hudson',
    'Zachery Jaskolski III',
    'Mrs. Amber Gleason',
    'Kieran Feeney',
    'Morgan Boyle III',
    'Trycia Reynolds',
    'Letitia Legros',
    'Crystel Collier',
    'Boyd Cole',
    'Verda Lynch',
    'Darrel Heathcote',
    'Mekhi Guªann',
    'Sunny Emard',
    'Gennaro Murray I',
    'Ben Kuhic',
    'Magdalen Parker',
    'Rudy Block',
    'Nigel Pfeffer',
    'Moriah Boehm',
    'Elwyn Goodwin',
    'Bridgette Green',
    'Greyson O Reilly',
    'Burnice Ferry',
    'Mr. Laurel Hermann',
    'Tyrell Renner',
    'Shyann Leffler',
    'Quinn Wuckert',
    'Heather Roob',
    'Madisen Veum',
    'Aurelio Marvin',
    'Norbert Bednar',
    'Chanelle Walsh',
    'Alexys Koss',
    'Myah Cole',
    'Ryan Marvin',
    'Dannie Abbott',
    'Izabella Zboncak',
    'Miss Gay McDermott',
    'Mrs. Lera Brakus',
    'Tatyana Towne',
    'Dr. Alfonzo Abernathy',
    'Damaris Hermiston',
    'Julius Howell',
    'Geraldine Beatty',
    'Carmela Leannon',
    'Aidan Greenholt',
    'Miss Ibrahim White',
    'Shana Dibbert',
    'Alvina Brown',
    'Cristobal Cummings',
    'Leonora Dach',
    'Mattie Buckridge',
    'Timmothy Collier',
    'Jed Morissette V'
];


$livros = [];

foreach ($compradores as $nomeComprador) {
    $livroPhp = new Livro('Padrões de Projeto em PHP 7.2', 'PHP');
    $livroPhp->setNomeTitular($nomeComprador);

    $livros[] = $livroPhp;
}

echo '<pre>';
print_r($livros);

$total1 = microtime(true) - $inicio1;
echo 'Tempo de execução do primeiro script: ' . $total1;